import type { visitSelectT } from './db/schema';

export const data: visitSelectT[] = [
  {
    id: 238,
    companyName: '武阳市俊驰物流有限责任公司',
    visitTime: new Date('2025-04-18T15:04:05.996Z'),
    visitType: '电话联系',
    visitedPerson: '鲜斌',
    visitedPersonPosition: 'Analyst',
    visitedPersonPhone: '16743712090',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 266,
    companyName: '陕西省昊然建设股份有限公司',
    visitTime: new Date('2025-04-18T04:25:10.705Z'),
    visitType: '微信交流',
    visitedPerson: '袁家明',
    visitedPersonPosition: 'Administrator',
    visitedPersonPhone: '15291990336',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand:
      'Cras aggero arca deleo tener ullus temperantia tempore deprecator.\nAcceptus ullam varietas audacia tondeo vulgus aduro temporibus.\nCupiditas summopere sequi adfero blandior.\nCubo tremo arma demonstro amaritudo sumptus caterva comptus cilicium ut.',
    isCompleted: false,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 412,
    companyName: '甘肃省金鑫物流有限公司',
    visitTime: new Date('2025-04-16T19:59:48.386Z'),
    visitType: '电话联系',
    visitedPerson: '招刚',
    visitedPersonPosition: 'Associate',
    visitedPersonPhone: '15243334334',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand: 'Officia ex sonitus aequitas solvo.',
    isCompleted: false,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 465,
    companyName: '太头市皓轩建设有限责任公司',
    visitTime: new Date('2025-04-15T21:10:12.206Z'),
    visitType: '微信交流',
    visitedPerson: '问三锋',
    visitedPersonPosition: 'Consultant',
    visitedPersonPhone: '10653563722',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand: 'Adduco atque vito tamquam currus.',
    isCompleted: false,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 531,
    companyName: '重庆市煜城水产有限公司',
    visitTime: new Date('2025-04-15T08:06:33.533Z'),
    visitType: '实地走访',
    visitedPerson: '闾波',
    visitedPersonPosition: 'Executive',
    visitedPersonPhone: '15827953133',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 349,
    companyName: '广西壮族自治区熠彤印刷股份有限公司',
    visitTime: new Date('2025-04-11T14:09:50.387Z'),
    visitType: '微信交流',
    visitedPerson: '郗超栋',
    visitedPersonPosition: 'Representative',
    visitedPersonPhone: '19053382330',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 995,
    companyName: '武头市楷瑞保险集团有限公司',
    visitTime: new Date('2025-04-09T03:17:47.173Z'),
    visitType: '电话联系',
    visitedPerson: '掌浩辰',
    visitedPersonPosition: 'Facilitator',
    visitedPersonPhone: '11095232560',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand: 'Vero absens strenuus sponte cupio ver solio uterque una.',
    isCompleted: false,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 551,
    companyName: '海码市昊然旅游发展股份有限公司',
    visitTime: new Date('2025-04-02T18:55:02.282Z'),
    visitType: '实地走访',
    visitedPerson: '运三锋',
    visitedPersonPosition: 'Facilitator',
    visitedPersonPhone: '10328311574',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 669,
    companyName: '河南省雨泽电力无限公司',
    visitTime: new Date('2025-03-26T05:03:32.272Z'),
    visitType: '电话联系',
    visitedPerson: '逄梓涵',
    visitedPersonPosition: 'Engineer',
    visitedPersonPhone: '19037465938',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 761,
    companyName: '安徽省文博林业无限公司',
    visitTime: new Date('2025-03-22T15:29:22.205Z'),
    visitType: '微信交流',
    visitedPerson: '宏三锋',
    visitedPersonPosition: 'Facilitator',
    visitedPersonPhone: '15748934591',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 442,
    companyName: '福头市子骞传媒无限公司',
    visitTime: new Date('2025-03-17T23:42:02.135Z'),
    visitType: '电话联系',
    visitedPerson: '逄丽芬',
    visitedPersonPosition: 'Director',
    visitedPersonPhone: '18063615849',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 657,
    companyName: '江苏省远航物流股份有限公司',
    visitTime: new Date('2025-03-17T02:23:54.945Z'),
    visitType: '实地走访',
    visitedPerson: '改欣怡',
    visitedPersonPosition: 'Strategist',
    visitedPersonPhone: '17327987424',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 712,
    companyName: '上海市超栋网络科技无限公司',
    visitTime: new Date('2025-03-15T06:54:15.304Z'),
    visitType: '微信交流',
    visitedPerson: '毓国芳',
    visitedPersonPosition: 'Strategist',
    visitedPersonPhone: '10664719310',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand:
      'Voluptate ultio sophismata tergiversatio theologus varius carmen error suasoria.',
    isCompleted: true,
    completedDescription:
      'Ater eos vapulus.\nBeneficium uxor victoria aperte decipio voluntarius.\nAssumenda deinde casso.\nDedico facilis beneficium sui dedico magnam tactus.',
    remarkInformation: null,
    completionTime: new Date('2025-03-16T02:54:15.304Z'),
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 6,
    companyName: '衡安市哲新印刷股份有限公司',
    visitTime: new Date('2025-03-14T01:32:45.120Z'),
    visitType: '电话联系',
    visitedPerson: '黎馥君',
    visitedPersonPosition: 'Director',
    visitedPersonPhone: '13898272517',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 613,
    companyName: '成都市耀杰燃气有限责任公司',
    visitTime: new Date('2025-03-11T11:00:26.986Z'),
    visitType: '微信交流',
    visitedPerson: '桐娟',
    visitedPersonPosition: 'Planner',
    visitedPersonPhone: '15157147324',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand: 'Tamdiu asporto temperantia in aliquam.',
    isCompleted: true,
    completedDescription:
      'Timidus itaque vaco spectaculum saepe theologus territo.\nToties non terror sumo acidus ex.',
    remarkInformation: null,
    completionTime: new Date('2025-03-12T07:00:26.986Z'),
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 653,
    companyName: '新疆维吾尔自治区政君电力无限责任公司',
    visitTime: new Date('2025-02-28T23:12:02.332Z'),
    visitType: '实地走访',
    visitedPerson: '巧癸霖',
    visitedPersonPosition: 'Supervisor',
    visitedPersonPhone: '17047891737',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand:
      'Cedo atrox surculus doloribus crinis spero demulceo administratio sapiente tempora.',
    isCompleted: false,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 388,
    companyName: '青海省笑愚印刷无限公司',
    visitTime: new Date('2025-02-23T02:48:49.531Z'),
    visitType: '微信交流',
    visitedPerson: '泷安琪',
    visitedPersonPosition: 'Orchestrator',
    visitedPersonPhone: '12279417062',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 136,
    companyName: '海汉市雅鑫食品股份有限公司',
    visitTime: new Date('2025-02-20T02:56:22.088Z'),
    visitType: '微信交流',
    visitedPerson: '奉子豪',
    visitedPersonPosition: 'Officer',
    visitedPersonPhone: '17459418730',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand:
      'Trucido vilis cohors porro voluptatem temporibus similique antepono tergum tollo.\nTheatrum pauci solutio cedo catena crustulum quibusdam vero.\nCibo arto summopere solum denuncio advenio texo.\nAlienus reprehenderit tertius aequitas.',
    isCompleted: false,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 217,
    companyName: '河北省聪健网络科技（集团）有限公司',
    visitTime: new Date('2025-02-15T16:05:24.388Z'),
    visitType: '微信交流',
    visitedPerson: '力梓豪',
    visitedPersonPosition: 'Representative',
    visitedPersonPhone: '17800218422',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 273,
    companyName: '江苏省荣轩林业有限公司',
    visitTime: new Date('2025-02-07T01:07:50.469Z'),
    visitType: '微信交流',
    visitedPerson: '佛三锋',
    visitedPersonPosition: 'Strategist',
    visitedPersonPhone: '11245063543',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand:
      'Carus acsi asper quam acidus talis vivo debeo magnam teres.\nAmet eius cunae commodi.',
    isCompleted: false,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 248,
    companyName: '内蒙古自治区黎昕燃气无限责任公司',
    visitTime: new Date('2025-02-06T10:37:52.532Z'),
    visitType: '实地走访',
    visitedPerson: '府海燕',
    visitedPersonPosition: 'Assistant',
    visitedPersonPhone: '19093661834',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 735,
    companyName: '宁夏回族自治区靖琪矿业集团有限公司',
    visitTime: new Date('2025-02-04T21:10:44.945Z'),
    visitType: '微信交流',
    visitedPerson: '仲丽',
    visitedPersonPosition: 'Agent',
    visitedPersonPhone: '10596901235',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand:
      'Quibusdam explicabo amissio.\nVoluptates qui cubo.\nBlanditiis defungo vesper truculenter iusto xiphias dolore.\nTermes aro aurum expedita degero sumo.',
    isCompleted: true,
    completedDescription: 'Pax utroque complectus vitium vilis deleo convoco.',
    remarkInformation: null,
    completionTime: new Date('2025-02-05T17:10:44.945Z'),
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 781,
    companyName: '宁夏回族自治区浩宇传媒（集团）有限公司',
    visitTime: new Date('2025-01-26T09:13:55.210Z'),
    visitType: '微信交流',
    visitedPerson: '绍红',
    visitedPersonPosition: 'Strategist',
    visitedPersonPhone: '12801789175',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand:
      'Vomito tabesco conspergo.\nSurculus animus maiores causa terminatio theatrum laborum correptius.\nAter amissio crepusculum corona adsuesco.\nAgnitio adfectus curo peior viscus.\nDemulceo volup calco apostolus voluptatum decimus sordeo ullam.',
    isCompleted: true,
    completedDescription: 'Animi pecto deputo vir utpote pecco.',
    remarkInformation: null,
    completionTime: new Date('2025-01-27T05:13:55.210Z'),
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 965,
    companyName: '包头市雅婷网络科技（集团）有限公司',
    visitTime: new Date('2025-01-18T02:26:26.953Z'),
    visitType: '电话联系',
    visitedPerson: '萨浩辰',
    visitedPersonPosition: 'Coordinator',
    visitedPersonPhone: '12541381808',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand:
      'Sortitus maiores desparatus demulceo decipio spero sophismata trepide corrigo.\nDeficio astrum umquam strues deporto cupio vesper debitis.\nTermes barba infit varietas.\nCulpo trucido deludo alo adeptio contego.',
    isCompleted: false,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 271,
    companyName: '重庆市潇然电力无限公司',
    visitTime: new Date('2025-01-17T01:56:25.047Z'),
    visitType: '电话联系',
    visitedPerson: '丙雯静',
    visitedPersonPosition: 'Liaison',
    visitedPersonPhone: '19247284347',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 501,
    companyName: '北林市伟祺燃气无限公司',
    visitTime: new Date('2025-01-15T07:57:22.376Z'),
    visitType: '实地走访',
    visitedPerson: '由浩然',
    visitedPersonPosition: 'Administrator',
    visitedPersonPhone: '11178127321',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand: 'Arcus provident tamquam vacuus vereor apud.\nVulgo nemo rem.',
    isCompleted: true,
    completedDescription:
      'Acies bardus adiuvo quos.\nAcies ante quis textilis contego vallum cauda claro depromo.\nAveho trado audax aranea undique incidunt cruciamentum.\nCado esse adimpleo temeritas laboriosam nobis magnam.\nCelebrer vado aggredior.',
    remarkInformation: null,
    completionTime: new Date('2025-01-16T03:57:22.376Z'),
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 660,
    companyName: '衡头市昊然矿业（集团）有限公司',
    visitTime: new Date('2025-01-08T09:23:00.253Z'),
    visitType: '电话联系',
    visitedPerson: '司丽萍',
    visitedPersonPosition: 'Administrator',
    visitedPersonPhone: '13629761285',
    visitSituation: '正常走访',
    hasCompanyDemand: false,
    companyDemand: null,
    isCompleted: null,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 485,
    companyName: '海南省敬阳电力有限责任公司',
    visitTime: new Date('2025-01-06T10:33:00.245Z'),
    visitType: '实地走访',
    visitedPerson: '玄国荣',
    visitedPersonPosition: 'Designer',
    visitedPersonPhone: '15050643603',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand:
      'Dolorem cur vitiosus cilicium universe.\nSuscipit calcar crux dedico curia velut tardus optio uredo.\nFugit sophismata veritas suggero vulnus artificiose allatus alter.\nDelibero reiciendis sufficio.\nUlterius viduo statua terminatio talis crepusculum aer pauci.',
    isCompleted: true,
    completedDescription:
      'Adsum vindico ago pauper suscipio absconditus certus vel expedita cupressus.\nCui terra adulescens.',
    remarkInformation: null,
    completionTime: new Date('2025-01-07T06:33:00.245Z'),
    completionPersonName: null,
    completionRemark: null,
  },
  {
    id: 903,
    companyName: '云南省浩宇物流股份有限公司',
    visitTime: new Date('2025-01-04T10:58:43.407Z'),
    visitType: '实地走访',
    visitedPerson: '牢雨桐',
    visitedPersonPosition: 'Supervisor',
    visitedPersonPhone: '13343901841',
    visitSituation: '正常走访',
    hasCompanyDemand: true,
    companyDemand: 'Conatus deorsum deprecator beatae careo.',
    isCompleted: false,
    completedDescription: null,
    remarkInformation: null,
    completionTime: null,
    completionPersonName: null,
    completionRemark: null,
  },
];
