/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestclientImport } from './routes/testclient'
import { Route as Test4Import } from './routes/test4'
import { Route as Test3Import } from './routes/test3'
import { Route as Test2Import } from './routes/test2'
import { Route as TestImport } from './routes/test'
import { Route as Table2Import } from './routes/table2'
import { Route as TableImport } from './routes/table'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardAddCompanyImport } from './routes/dashboard/addCompany'
import { Route as DashboardListCopImport } from './routes/dashboard/ListCop'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLoginImport } from './routes/auth/login'

// Create/Update Routes

const TestclientRoute = TestclientImport.update({
  id: '/testclient',
  path: '/testclient',
  getParentRoute: () => rootRoute,
} as any)

const Test4Route = Test4Import.update({
  id: '/test4',
  path: '/test4',
  getParentRoute: () => rootRoute,
} as any)

const Test3Route = Test3Import.update({
  id: '/test3',
  path: '/test3',
  getParentRoute: () => rootRoute,
} as any)

const Test2Route = Test2Import.update({
  id: '/test2',
  path: '/test2',
  getParentRoute: () => rootRoute,
} as any)

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const Table2Route = Table2Import.update({
  id: '/table2',
  path: '/table2',
  getParentRoute: () => rootRoute,
} as any)

const TableRoute = TableImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardAddCompanyRoute = DashboardAddCompanyImport.update({
  id: '/addCompany',
  path: '/addCompany',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardListCopRoute = DashboardListCopImport.update({
  id: '/ListCop',
  path: '/ListCop',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableImport
      parentRoute: typeof rootRoute
    }
    '/table2': {
      id: '/table2'
      path: '/table2'
      fullPath: '/table2'
      preLoaderRoute: typeof Table2Import
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/test2': {
      id: '/test2'
      path: '/test2'
      fullPath: '/test2'
      preLoaderRoute: typeof Test2Import
      parentRoute: typeof rootRoute
    }
    '/test3': {
      id: '/test3'
      path: '/test3'
      fullPath: '/test3'
      preLoaderRoute: typeof Test3Import
      parentRoute: typeof rootRoute
    }
    '/test4': {
      id: '/test4'
      path: '/test4'
      fullPath: '/test4'
      preLoaderRoute: typeof Test4Import
      parentRoute: typeof rootRoute
    }
    '/testclient': {
      id: '/testclient'
      path: '/testclient'
      fullPath: '/testclient'
      preLoaderRoute: typeof TestclientImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthRouteImport
    }
    '/dashboard/ListCop': {
      id: '/dashboard/ListCop'
      path: '/ListCop'
      fullPath: '/dashboard/ListCop'
      preLoaderRoute: typeof DashboardListCopImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/addCompany': {
      id: '/dashboard/addCompany'
      path: '/addCompany'
      fullPath: '/dashboard/addCompany'
      preLoaderRoute: typeof DashboardAddCompanyImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardListCopRoute: typeof DashboardListCopRoute
  DashboardAddCompanyRoute: typeof DashboardAddCompanyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardListCopRoute: DashboardListCopRoute,
  DashboardAddCompanyRoute: DashboardAddCompanyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/table': typeof TableRoute
  '/table2': typeof Table2Route
  '/test': typeof TestRoute
  '/test2': typeof Test2Route
  '/test3': typeof Test3Route
  '/test4': typeof Test4Route
  '/testclient': typeof TestclientRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/ListCop': typeof DashboardListCopRoute
  '/dashboard/addCompany': typeof DashboardAddCompanyRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/table': typeof TableRoute
  '/table2': typeof Table2Route
  '/test': typeof TestRoute
  '/test2': typeof Test2Route
  '/test3': typeof Test3Route
  '/test4': typeof Test4Route
  '/testclient': typeof TestclientRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/ListCop': typeof DashboardListCopRoute
  '/dashboard/addCompany': typeof DashboardAddCompanyRoute
  '/dashboard': typeof DashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/table': typeof TableRoute
  '/table2': typeof Table2Route
  '/test': typeof TestRoute
  '/test2': typeof Test2Route
  '/test3': typeof Test3Route
  '/test4': typeof Test4Route
  '/testclient': typeof TestclientRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/ListCop': typeof DashboardListCopRoute
  '/dashboard/addCompany': typeof DashboardAddCompanyRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/table'
    | '/table2'
    | '/test'
    | '/test2'
    | '/test3'
    | '/test4'
    | '/testclient'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/ListCop'
    | '/dashboard/addCompany'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/table'
    | '/table2'
    | '/test'
    | '/test2'
    | '/test3'
    | '/test4'
    | '/testclient'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/ListCop'
    | '/dashboard/addCompany'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/table'
    | '/table2'
    | '/test'
    | '/test2'
    | '/test3'
    | '/test4'
    | '/testclient'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/ListCop'
    | '/dashboard/addCompany'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  TableRoute: typeof TableRoute
  Table2Route: typeof Table2Route
  TestRoute: typeof TestRoute
  Test2Route: typeof Test2Route
  Test3Route: typeof Test3Route
  Test4Route: typeof Test4Route
  TestclientRoute: typeof TestclientRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  TableRoute: TableRoute,
  Table2Route: Table2Route,
  TestRoute: TestRoute,
  Test2Route: Test2Route,
  Test3Route: Test3Route,
  Test4Route: Test4Route,
  TestclientRoute: TestclientRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/dashboard",
        "/table",
        "/table2",
        "/test",
        "/test2",
        "/test3",
        "/test4",
        "/testclient"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/login",
        "/auth/signup"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/ListCop",
        "/dashboard/addCompany",
        "/dashboard/"
      ]
    },
    "/table": {
      "filePath": "table.tsx"
    },
    "/table2": {
      "filePath": "table2.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/test2": {
      "filePath": "test2.tsx"
    },
    "/test3": {
      "filePath": "test3.tsx"
    },
    "/test4": {
      "filePath": "test4.tsx"
    },
    "/testclient": {
      "filePath": "testclient.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx",
      "parent": "/auth"
    },
    "/dashboard/ListCop": {
      "filePath": "dashboard/ListCop.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/addCompany": {
      "filePath": "dashboard/addCompany.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
