/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestclientImport } from './routes/testclient'
import { Route as TestvisitImport } from './routes/test_visit'
import { Route as Test7Import } from './routes/test7'
import { Route as Test6Import } from './routes/test6'
import { Route as Test5Import } from './routes/test5'
import { Route as Test4Import } from './routes/test4'
import { Route as Test3Import } from './routes/test3'
import { Route as Test2Import } from './routes/test2'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardHistoryVisitImport } from './routes/dashboard/historyVisit'
import { Route as DashboardAddCompanyImport } from './routes/dashboard/addCompany'
import { Route as DashboardListCopImport } from './routes/dashboard/ListCop'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLoginImport } from './routes/auth/login'

// Create/Update Routes

const TestclientRoute = TestclientImport.update({
  id: '/testclient',
  path: '/testclient',
  getParentRoute: () => rootRoute,
} as any)

const TestvisitRoute = TestvisitImport.update({
  id: '/test_visit',
  path: '/test_visit',
  getParentRoute: () => rootRoute,
} as any)

const Test7Route = Test7Import.update({
  id: '/test7',
  path: '/test7',
  getParentRoute: () => rootRoute,
} as any)

const Test6Route = Test6Import.update({
  id: '/test6',
  path: '/test6',
  getParentRoute: () => rootRoute,
} as any)

const Test5Route = Test5Import.update({
  id: '/test5',
  path: '/test5',
  getParentRoute: () => rootRoute,
} as any)

const Test4Route = Test4Import.update({
  id: '/test4',
  path: '/test4',
  getParentRoute: () => rootRoute,
} as any)

const Test3Route = Test3Import.update({
  id: '/test3',
  path: '/test3',
  getParentRoute: () => rootRoute,
} as any)

const Test2Route = Test2Import.update({
  id: '/test2',
  path: '/test2',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardHistoryVisitRoute = DashboardHistoryVisitImport.update({
  id: '/historyVisit',
  path: '/historyVisit',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardAddCompanyRoute = DashboardAddCompanyImport.update({
  id: '/addCompany',
  path: '/addCompany',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardListCopRoute = DashboardListCopImport.update({
  id: '/ListCop',
  path: '/ListCop',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/test2': {
      id: '/test2'
      path: '/test2'
      fullPath: '/test2'
      preLoaderRoute: typeof Test2Import
      parentRoute: typeof rootRoute
    }
    '/test3': {
      id: '/test3'
      path: '/test3'
      fullPath: '/test3'
      preLoaderRoute: typeof Test3Import
      parentRoute: typeof rootRoute
    }
    '/test4': {
      id: '/test4'
      path: '/test4'
      fullPath: '/test4'
      preLoaderRoute: typeof Test4Import
      parentRoute: typeof rootRoute
    }
    '/test5': {
      id: '/test5'
      path: '/test5'
      fullPath: '/test5'
      preLoaderRoute: typeof Test5Import
      parentRoute: typeof rootRoute
    }
    '/test6': {
      id: '/test6'
      path: '/test6'
      fullPath: '/test6'
      preLoaderRoute: typeof Test6Import
      parentRoute: typeof rootRoute
    }
    '/test7': {
      id: '/test7'
      path: '/test7'
      fullPath: '/test7'
      preLoaderRoute: typeof Test7Import
      parentRoute: typeof rootRoute
    }
    '/test_visit': {
      id: '/test_visit'
      path: '/test_visit'
      fullPath: '/test_visit'
      preLoaderRoute: typeof TestvisitImport
      parentRoute: typeof rootRoute
    }
    '/testclient': {
      id: '/testclient'
      path: '/testclient'
      fullPath: '/testclient'
      preLoaderRoute: typeof TestclientImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthRouteImport
    }
    '/dashboard/ListCop': {
      id: '/dashboard/ListCop'
      path: '/ListCop'
      fullPath: '/dashboard/ListCop'
      preLoaderRoute: typeof DashboardListCopImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/addCompany': {
      id: '/dashboard/addCompany'
      path: '/addCompany'
      fullPath: '/dashboard/addCompany'
      preLoaderRoute: typeof DashboardAddCompanyImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/historyVisit': {
      id: '/dashboard/historyVisit'
      path: '/historyVisit'
      fullPath: '/dashboard/historyVisit'
      preLoaderRoute: typeof DashboardHistoryVisitImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardListCopRoute: typeof DashboardListCopRoute
  DashboardAddCompanyRoute: typeof DashboardAddCompanyRoute
  DashboardHistoryVisitRoute: typeof DashboardHistoryVisitRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardListCopRoute: DashboardListCopRoute,
  DashboardAddCompanyRoute: DashboardAddCompanyRoute,
  DashboardHistoryVisitRoute: DashboardHistoryVisitRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/test2': typeof Test2Route
  '/test3': typeof Test3Route
  '/test4': typeof Test4Route
  '/test5': typeof Test5Route
  '/test6': typeof Test6Route
  '/test7': typeof Test7Route
  '/test_visit': typeof TestvisitRoute
  '/testclient': typeof TestclientRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/ListCop': typeof DashboardListCopRoute
  '/dashboard/addCompany': typeof DashboardAddCompanyRoute
  '/dashboard/historyVisit': typeof DashboardHistoryVisitRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/test2': typeof Test2Route
  '/test3': typeof Test3Route
  '/test4': typeof Test4Route
  '/test5': typeof Test5Route
  '/test6': typeof Test6Route
  '/test7': typeof Test7Route
  '/test_visit': typeof TestvisitRoute
  '/testclient': typeof TestclientRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/ListCop': typeof DashboardListCopRoute
  '/dashboard/addCompany': typeof DashboardAddCompanyRoute
  '/dashboard/historyVisit': typeof DashboardHistoryVisitRoute
  '/dashboard': typeof DashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/test2': typeof Test2Route
  '/test3': typeof Test3Route
  '/test4': typeof Test4Route
  '/test5': typeof Test5Route
  '/test6': typeof Test6Route
  '/test7': typeof Test7Route
  '/test_visit': typeof TestvisitRoute
  '/testclient': typeof TestclientRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/ListCop': typeof DashboardListCopRoute
  '/dashboard/addCompany': typeof DashboardAddCompanyRoute
  '/dashboard/historyVisit': typeof DashboardHistoryVisitRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/test2'
    | '/test3'
    | '/test4'
    | '/test5'
    | '/test6'
    | '/test7'
    | '/test_visit'
    | '/testclient'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/ListCop'
    | '/dashboard/addCompany'
    | '/dashboard/historyVisit'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/test2'
    | '/test3'
    | '/test4'
    | '/test5'
    | '/test6'
    | '/test7'
    | '/test_visit'
    | '/testclient'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/ListCop'
    | '/dashboard/addCompany'
    | '/dashboard/historyVisit'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/test2'
    | '/test3'
    | '/test4'
    | '/test5'
    | '/test6'
    | '/test7'
    | '/test_visit'
    | '/testclient'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/ListCop'
    | '/dashboard/addCompany'
    | '/dashboard/historyVisit'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  Test2Route: typeof Test2Route
  Test3Route: typeof Test3Route
  Test4Route: typeof Test4Route
  Test5Route: typeof Test5Route
  Test6Route: typeof Test6Route
  Test7Route: typeof Test7Route
  TestvisitRoute: typeof TestvisitRoute
  TestclientRoute: typeof TestclientRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  Test2Route: Test2Route,
  Test3Route: Test3Route,
  Test4Route: Test4Route,
  Test5Route: Test5Route,
  Test6Route: Test6Route,
  Test7Route: Test7Route,
  TestvisitRoute: TestvisitRoute,
  TestclientRoute: TestclientRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/dashboard",
        "/test2",
        "/test3",
        "/test4",
        "/test5",
        "/test6",
        "/test7",
        "/test_visit",
        "/testclient"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/login",
        "/auth/signup"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/ListCop",
        "/dashboard/addCompany",
        "/dashboard/historyVisit",
        "/dashboard/"
      ]
    },
    "/test2": {
      "filePath": "test2.tsx"
    },
    "/test3": {
      "filePath": "test3.tsx"
    },
    "/test4": {
      "filePath": "test4.tsx"
    },
    "/test5": {
      "filePath": "test5.tsx"
    },
    "/test6": {
      "filePath": "test6.tsx"
    },
    "/test7": {
      "filePath": "test7.tsx"
    },
    "/test_visit": {
      "filePath": "test_visit.tsx"
    },
    "/testclient": {
      "filePath": "testclient.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx",
      "parent": "/auth"
    },
    "/dashboard/ListCop": {
      "filePath": "dashboard/ListCop.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/addCompany": {
      "filePath": "dashboard/addCompany.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/historyVisit": {
      "filePath": "dashboard/historyVisit.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
