/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestclientRouteImport } from './routes/testclient'
import { Route as Test9HeaderpicRouteImport } from './routes/test9-headerpic'
import { Route as Test8HeaderRouteImport } from './routes/test8-header'
import { Route as Test7RouteImport } from './routes/test7'
import { Route as Test6RouteImport } from './routes/test6'
import { Route as Test5RouteImport } from './routes/test5'
import { Route as Test4RouteImport } from './routes/test4'
import { Route as Test3RouteImport } from './routes/test3'
import { Route as Test2RouteImport } from './routes/test2'
import { Route as Test17RouteImport } from './routes/test17'
import { Route as Test15RouteImport } from './routes/test15'
import { Route as Test14WenjuanRouteImport } from './routes/test14-wenjuan'
import { Route as Test13CustomersRouteImport } from './routes/test13-customers'
import { Route as Test11CardsRouteImport } from './routes/test11-cards'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardNewVisitRouteImport } from './routes/dashboard/new-visit'
import { Route as DashboardListCopRouteImport } from './routes/dashboard/list-cop'
import { Route as DashboardHistoryVisitRouteImport } from './routes/dashboard/history-visit'
import { Route as DashboardAddCompanyRouteImport } from './routes/dashboard/add-company'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TestclientRoute = TestclientRouteImport.update({
  id: '/testclient',
  path: '/testclient',
  getParentRoute: () => rootRouteImport,
} as any)
const Test9HeaderpicRoute = Test9HeaderpicRouteImport.update({
  id: '/test9-headerpic',
  path: '/test9-headerpic',
  getParentRoute: () => rootRouteImport,
} as any)
const Test8HeaderRoute = Test8HeaderRouteImport.update({
  id: '/test8-header',
  path: '/test8-header',
  getParentRoute: () => rootRouteImport,
} as any)
const Test7Route = Test7RouteImport.update({
  id: '/test7',
  path: '/test7',
  getParentRoute: () => rootRouteImport,
} as any)
const Test6Route = Test6RouteImport.update({
  id: '/test6',
  path: '/test6',
  getParentRoute: () => rootRouteImport,
} as any)
const Test5Route = Test5RouteImport.update({
  id: '/test5',
  path: '/test5',
  getParentRoute: () => rootRouteImport,
} as any)
const Test4Route = Test4RouteImport.update({
  id: '/test4',
  path: '/test4',
  getParentRoute: () => rootRouteImport,
} as any)
const Test3Route = Test3RouteImport.update({
  id: '/test3',
  path: '/test3',
  getParentRoute: () => rootRouteImport,
} as any)
const Test2Route = Test2RouteImport.update({
  id: '/test2',
  path: '/test2',
  getParentRoute: () => rootRouteImport,
} as any)
const Test17Route = Test17RouteImport.update({
  id: '/test17',
  path: '/test17',
  getParentRoute: () => rootRouteImport,
} as any)
const Test15Route = Test15RouteImport.update({
  id: '/test15',
  path: '/test15',
  getParentRoute: () => rootRouteImport,
} as any)
const Test14WenjuanRoute = Test14WenjuanRouteImport.update({
  id: '/test14-wenjuan',
  path: '/test14-wenjuan',
  getParentRoute: () => rootRouteImport,
} as any)
const Test13CustomersRoute = Test13CustomersRouteImport.update({
  id: '/test13-customers',
  path: '/test13-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const Test11CardsRoute = Test11CardsRouteImport.update({
  id: '/test11-cards',
  path: '/test11-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNewVisitRoute = DashboardNewVisitRouteImport.update({
  id: '/new-visit',
  path: '/new-visit',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardListCopRoute = DashboardListCopRouteImport.update({
  id: '/list-cop',
  path: '/list-cop',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHistoryVisitRoute = DashboardHistoryVisitRouteImport.update({
  id: '/history-visit',
  path: '/history-visit',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAddCompanyRoute = DashboardAddCompanyRouteImport.update({
  id: '/add-company',
  path: '/add-company',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/test11-cards': typeof Test11CardsRoute
  '/test13-customers': typeof Test13CustomersRoute
  '/test14-wenjuan': typeof Test14WenjuanRoute
  '/test15': typeof Test15Route
  '/test17': typeof Test17Route
  '/test2': typeof Test2Route
  '/test3': typeof Test3Route
  '/test4': typeof Test4Route
  '/test5': typeof Test5Route
  '/test6': typeof Test6Route
  '/test7': typeof Test7Route
  '/test8-header': typeof Test8HeaderRoute
  '/test9-headerpic': typeof Test9HeaderpicRoute
  '/testclient': typeof TestclientRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/add-company': typeof DashboardAddCompanyRoute
  '/dashboard/history-visit': typeof DashboardHistoryVisitRoute
  '/dashboard/list-cop': typeof DashboardListCopRoute
  '/dashboard/new-visit': typeof DashboardNewVisitRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/test11-cards': typeof Test11CardsRoute
  '/test13-customers': typeof Test13CustomersRoute
  '/test14-wenjuan': typeof Test14WenjuanRoute
  '/test15': typeof Test15Route
  '/test17': typeof Test17Route
  '/test2': typeof Test2Route
  '/test3': typeof Test3Route
  '/test4': typeof Test4Route
  '/test5': typeof Test5Route
  '/test6': typeof Test6Route
  '/test7': typeof Test7Route
  '/test8-header': typeof Test8HeaderRoute
  '/test9-headerpic': typeof Test9HeaderpicRoute
  '/testclient': typeof TestclientRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/add-company': typeof DashboardAddCompanyRoute
  '/dashboard/history-visit': typeof DashboardHistoryVisitRoute
  '/dashboard/list-cop': typeof DashboardListCopRoute
  '/dashboard/new-visit': typeof DashboardNewVisitRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/test11-cards': typeof Test11CardsRoute
  '/test13-customers': typeof Test13CustomersRoute
  '/test14-wenjuan': typeof Test14WenjuanRoute
  '/test15': typeof Test15Route
  '/test17': typeof Test17Route
  '/test2': typeof Test2Route
  '/test3': typeof Test3Route
  '/test4': typeof Test4Route
  '/test5': typeof Test5Route
  '/test6': typeof Test6Route
  '/test7': typeof Test7Route
  '/test8-header': typeof Test8HeaderRoute
  '/test9-headerpic': typeof Test9HeaderpicRoute
  '/testclient': typeof TestclientRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/add-company': typeof DashboardAddCompanyRoute
  '/dashboard/history-visit': typeof DashboardHistoryVisitRoute
  '/dashboard/list-cop': typeof DashboardListCopRoute
  '/dashboard/new-visit': typeof DashboardNewVisitRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/test11-cards'
    | '/test13-customers'
    | '/test14-wenjuan'
    | '/test15'
    | '/test17'
    | '/test2'
    | '/test3'
    | '/test4'
    | '/test5'
    | '/test6'
    | '/test7'
    | '/test8-header'
    | '/test9-headerpic'
    | '/testclient'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/add-company'
    | '/dashboard/history-visit'
    | '/dashboard/list-cop'
    | '/dashboard/new-visit'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/test11-cards'
    | '/test13-customers'
    | '/test14-wenjuan'
    | '/test15'
    | '/test17'
    | '/test2'
    | '/test3'
    | '/test4'
    | '/test5'
    | '/test6'
    | '/test7'
    | '/test8-header'
    | '/test9-headerpic'
    | '/testclient'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/add-company'
    | '/dashboard/history-visit'
    | '/dashboard/list-cop'
    | '/dashboard/new-visit'
    | '/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/test11-cards'
    | '/test13-customers'
    | '/test14-wenjuan'
    | '/test15'
    | '/test17'
    | '/test2'
    | '/test3'
    | '/test4'
    | '/test5'
    | '/test6'
    | '/test7'
    | '/test8-header'
    | '/test9-headerpic'
    | '/testclient'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/add-company'
    | '/dashboard/history-visit'
    | '/dashboard/list-cop'
    | '/dashboard/new-visit'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  Test11CardsRoute: typeof Test11CardsRoute
  Test13CustomersRoute: typeof Test13CustomersRoute
  Test14WenjuanRoute: typeof Test14WenjuanRoute
  Test15Route: typeof Test15Route
  Test17Route: typeof Test17Route
  Test2Route: typeof Test2Route
  Test3Route: typeof Test3Route
  Test4Route: typeof Test4Route
  Test5Route: typeof Test5Route
  Test6Route: typeof Test6Route
  Test7Route: typeof Test7Route
  Test8HeaderRoute: typeof Test8HeaderRoute
  Test9HeaderpicRoute: typeof Test9HeaderpicRoute
  TestclientRoute: typeof TestclientRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testclient': {
      id: '/testclient'
      path: '/testclient'
      fullPath: '/testclient'
      preLoaderRoute: typeof TestclientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test9-headerpic': {
      id: '/test9-headerpic'
      path: '/test9-headerpic'
      fullPath: '/test9-headerpic'
      preLoaderRoute: typeof Test9HeaderpicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test8-header': {
      id: '/test8-header'
      path: '/test8-header'
      fullPath: '/test8-header'
      preLoaderRoute: typeof Test8HeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test7': {
      id: '/test7'
      path: '/test7'
      fullPath: '/test7'
      preLoaderRoute: typeof Test7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test6': {
      id: '/test6'
      path: '/test6'
      fullPath: '/test6'
      preLoaderRoute: typeof Test6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test5': {
      id: '/test5'
      path: '/test5'
      fullPath: '/test5'
      preLoaderRoute: typeof Test5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test4': {
      id: '/test4'
      path: '/test4'
      fullPath: '/test4'
      preLoaderRoute: typeof Test4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test3': {
      id: '/test3'
      path: '/test3'
      fullPath: '/test3'
      preLoaderRoute: typeof Test3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test2': {
      id: '/test2'
      path: '/test2'
      fullPath: '/test2'
      preLoaderRoute: typeof Test2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test17': {
      id: '/test17'
      path: '/test17'
      fullPath: '/test17'
      preLoaderRoute: typeof Test17RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test15': {
      id: '/test15'
      path: '/test15'
      fullPath: '/test15'
      preLoaderRoute: typeof Test15RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test14-wenjuan': {
      id: '/test14-wenjuan'
      path: '/test14-wenjuan'
      fullPath: '/test14-wenjuan'
      preLoaderRoute: typeof Test14WenjuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test13-customers': {
      id: '/test13-customers'
      path: '/test13-customers'
      fullPath: '/test13-customers'
      preLoaderRoute: typeof Test13CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test11-cards': {
      id: '/test11-cards'
      path: '/test11-cards'
      fullPath: '/test11-cards'
      preLoaderRoute: typeof Test11CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/new-visit': {
      id: '/dashboard/new-visit'
      path: '/new-visit'
      fullPath: '/dashboard/new-visit'
      preLoaderRoute: typeof DashboardNewVisitRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/list-cop': {
      id: '/dashboard/list-cop'
      path: '/list-cop'
      fullPath: '/dashboard/list-cop'
      preLoaderRoute: typeof DashboardListCopRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/history-visit': {
      id: '/dashboard/history-visit'
      path: '/history-visit'
      fullPath: '/dashboard/history-visit'
      preLoaderRoute: typeof DashboardHistoryVisitRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/add-company': {
      id: '/dashboard/add-company'
      path: '/add-company'
      fullPath: '/dashboard/add-company'
      preLoaderRoute: typeof DashboardAddCompanyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAddCompanyRoute: typeof DashboardAddCompanyRoute
  DashboardHistoryVisitRoute: typeof DashboardHistoryVisitRoute
  DashboardListCopRoute: typeof DashboardListCopRoute
  DashboardNewVisitRoute: typeof DashboardNewVisitRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAddCompanyRoute: DashboardAddCompanyRoute,
  DashboardHistoryVisitRoute: DashboardHistoryVisitRoute,
  DashboardListCopRoute: DashboardListCopRoute,
  DashboardNewVisitRoute: DashboardNewVisitRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  Test11CardsRoute: Test11CardsRoute,
  Test13CustomersRoute: Test13CustomersRoute,
  Test14WenjuanRoute: Test14WenjuanRoute,
  Test15Route: Test15Route,
  Test17Route: Test17Route,
  Test2Route: Test2Route,
  Test3Route: Test3Route,
  Test4Route: Test4Route,
  Test5Route: Test5Route,
  Test6Route: Test6Route,
  Test7Route: Test7Route,
  Test8HeaderRoute: Test8HeaderRoute,
  Test9HeaderpicRoute: Test9HeaderpicRoute,
  TestclientRoute: TestclientRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
